# **Intelligent Systems for Bioinformatics**
### Exercise 1: NumPy array Indexing/Slicing

1.1) In this exercise, we will use the iris dataset. Load 
the "iris.csv" using the appropriate method for this file 
type (use the new functions from the package).

In [1]:
from si.io.csv_file import read_csv

# Load the iris dataset
dataset_iris = read_csv('../datasets/iris/iris.csv', sep=',', features=True, label=True)

print(f"Dataset shape: {dataset_iris.shape()}")
print(f"X: {dataset_iris.X}")
print(f"y: {dataset_iris.y}")
print(f"X shape: {dataset_iris.X.shape}")
print(f"y shape: {dataset_iris.y.shape}")
print(f"Features: {dataset_iris.features}")
print(f"Label: {dataset_iris.label}")

Dataset shape: (150, 4)
X: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.

 1.2) Select the penultimate independent variable. 
What is the dimension of the resulting array?

In [2]:
# Select the penultimate independent variable
penultimate_feature = dataset_iris.X[:, -2]

# Get the dimension of the respective array
dimension = penultimate_feature.ndim
print(f"Dimension of the array: {dimension}")

Dimension of the array: 1


1.3) Select the last 10 samples from the iris dataset. 
What is the mean of the last 10 samples for each 
independent variable/feature?


In [3]:
import numpy as np

# Select the last 10 samples
last_10 = dataset_iris.X[-10:, :]

# Mean of the last 10 samples for each feature
last_10_mean = np.mean(last_10, axis=0)
print(f"Mean of the last 10 samples for each feature: {last_10_mean}")

Mean of the last 10 samples for each feature: [6.45 3.03 5.33 2.17]


1.4) Select all samples from the dataset with values 
less than or equal to 6 for all independent 
variables/features. How many samples do you obtain?

In [4]:
# Boolean mask with the condition
mask_14 = dataset_iris.X <= 6 

# Identify the samples that satisfy the condition
samples_14 = np.all(mask_14, axis=1)

# Select the samples that satisfy the condition
filtered_samples = np.sum(samples_14)
print(f"Number of samples with values less than or equal to 6: {filtered_samples}")

Number of samples with values less than or equal to 6: 89


1.5) Select all samples with a class/label different 
from 'Iris-setosa'. How many samples do you obtain?

In [5]:
# Booelan mask with the condition
mask_15 = dataset_iris.y != "Iris-setosa"

# Select the samples that satisfy the condition
samples_15 = np.sum(mask_15)
print(f"Number of samples with labels different from 'Iris-setosa': {samples_15}")

Number of samples with labels different from 'Iris-setosa': 100


### Exercise 2: NumPy array Indexing/Slicing

2.1) Add a method to the Dataset class that removes 
all samples containing at least one null value (NaN). 
Note that the resulting object should not contain null 
values in any independent feature/variable. Also, 
note that you should update the y vector by 
removing entries associated with the samples to be 
removed. You should use only NumPy functions.
 Method name: dropna

**dropna**

In [6]:
from si.data.dataset import Dataset
from si.io.csv_file import read_csv

dataset_iris_missing = read_csv('../datasets/iris/iris_missing_data.csv', sep=',', features=True, label=True)

print(f"Original shape: {dataset_iris_missing.shape()}")

# Apply dropna method
dataset_iris_missing.dropna()

print(f"Shape after 'dropna': {dataset_iris_missing.shape()}")

Original shape: (150, 4)
Shape after 'dropna': (134, 4)


 2.2) Add a method to the Dataset class that 
replaces all null values with another value or the 
mean or median of the feature/variable. Note that 
the resulting object should not contain null values 
in any independent feature/variable. You should 
use only NumPy functions.
 Method name: fillna

**fillna**

In [7]:
import numpy as np
import copy

# --- Example 1: Fill with a value (3) ---
print("Example 1: Fill with a value (3):")
d1 = copy.deepcopy(dataset_iris_missing) 
d1.fillna(value=3)

n_nans = np.sum(np.isnan(d1.X))
print(f"NaNs remaining: {n_nans}")
print(f"All NaNs filled with 3 in dataset: {n_nans == 0}")
print("-" * 30)

# --- Example 2: Fill with Mean ---
print("Example 2: Fill with mean:")
d2 = copy.deepcopy(dataset_iris_missing)
d2.fillna('mean')

n_nans = np.sum(np.isnan(d2.X))
print(f"NaNs remaining: {n_nans}")
print(f"All NaNs filled with mean in dataset: {n_nans == 0}")
print("-" * 30)

# --- Example 3: Fill with Median ---
print(f"Example 3: Fill with median:")
d3 = copy.deepcopy(dataset_iris_missing)
d3.fillna('median')

n_nans = np.sum(np.isnan(d3.X))
print(f"NaNs remaining: {n_nans}")
print(f"All NaNs filled with median in dataset: {n_nans == 0}")

Example 1: Fill with a value (3):
NaNs remaining: 0
All NaNs filled with 3 in dataset: True
------------------------------
Example 2: Fill with mean:


NaNs remaining: 0
All NaNs filled with mean in dataset: True
------------------------------
Example 3: Fill with median:
NaNs remaining: 0
All NaNs filled with median in dataset: True


2.3) Add a method to the Dataset class that 
removes a sample by its index. Note that you 
should also update the y vector by removing the 
entry associated with the sample to be removed. 
You should use only NumPy functions. 
Method name: remove_by_index

**remove_by_index**

In [ ]:
print("Original dataset")
print(f"X shape: {dataset_iris.X.shape}")
print(f"y shape: {dataset_iris.y.shape}")
print("-" * 30)

# Remove the last sample (index 149)
dataset_iris.remove_by_index(149)
print("After removing index 149")
print(f"X shape: {dataset_iris.X.shape}")
print(f"y shape: {dataset_iris.y.shape}")

Original dataset
X shape: (150, 4)
y shape: (150,)
------------------------------
After removing index 149
X shape: (149, 4)
y shape: (149,)
